#ifndef VP_BOARD_H
#define VP_BOARD_H

#include "driver/gpio.h"
#include "driver/ledc.h"
#include "driver/spi_master.h"
#include "driver/uart.h"

/*
 * VoltPilot ESP32-S3 板级配置。
 * 这里集中保存最新引脚图中的 GPIO、外设端口和调试参数，业务代码只引用宏，不散落硬编码。
 */

/* 功能开关：启用 2.13 寸黑白红三色墨水屏启动测试。 */
#define VP_ENABLE_DISPLAY 1
#define VP_ENABLE_ADC_SERVICE 1
#define VP_ENABLE_BMS_SERVICE 1
#define VP_ENABLE_STC_SERVICE 1
#define VP_ENABLE_UI_SERVICE 1
#define VP_ENABLE_STATE_SERVICE 1

/* 2.13 寸黑白红三色墨水屏：模块丝印 GND,VCC,SCL,SDA,RES,DC,CS,BUSY。 */
#define VP_EPD_HOST SPI2_HOST
#define VP_EPD_PIN_SCK GPIO_NUM_12
#define VP_EPD_PIN_MOSI GPIO_NUM_11
#define VP_EPD_PIN_CS GPIO_NUM_13
#define VP_EPD_PIN_DC GPIO_NUM_9
#define VP_EPD_PIN_RST GPIO_NUM_10
#define VP_EPD_PIN_BUSY GPIO_NUM_14
#define VP_EPD_SPI_CLOCK_HZ (400 * 1000)
#define VP_EPD_USE_SOFTWARE_SPI 1
#define VP_EPD_SOFTWARE_SPI_DELAY_US 5
#define VP_EPD_BUSY_ACTIVE_LEVEL 1
#define VP_EPD_BUSY_START_TIMEOUT_MS 10000
#define VP_EPD_BUSY_TIMEOUT_MS 30000
#define VP_EPD_REFRESH_FALLBACK_MS 5000
#define VP_EPD_RUN_INIT_REFRESH_PROBE 0
#define VP_EPD_BOOT_FULL_BLACK_TEST 0

/* STC8H 挡位采集 MCU 通信串口：TTL UART，采用 VoltPilot 自定义 Modbus RTU 风格协议。 */
#define VP_STC_UART_PORT UART_NUM_1
#define VP_STC_UART_BAUD_RATE 115200
#define VP_STC_PIN_TX GPIO_NUM_37
#define VP_STC_PIN_RX GPIO_NUM_38
#define VP_STC_RX_TIMEOUT_MS 10000
#define VP_STC_HEARTBEAT_INTERVAL_MS 1000
#define VP_STC_READ_GEAR_INTERVAL_MS 1000
#define VP_STC_READ_VERSION_INTERVAL_MS 10000

/* BMS 电池 RS485 通讯串口。RS485 模块无 DE/RE 方向控制脚。 */
#define VP_BMS_UART_PORT UART_NUM_2
#define VP_BMS_UART_BAUD_RATE 9600
#define VP_BMS_PIN_RX GPIO_NUM_8
#define VP_BMS_PIN_TX GPIO_NUM_18
#define VP_BMS_RX_TIMEOUT_MS 10000
#define VP_BMS_REQUEST_INTERVAL_MS 1000

/* 输出电压反馈 ADC。当前先输出 raw 与 ADC 引脚电压，真实分压比后续按硬件填入。 */
#define VP_ADC_PIN_24V GPIO_NUM_4
#define VP_ADC_PIN_5V GPIO_NUM_5
#define VP_ADC_PIN_36V GPIO_NUM_6
#define VP_ADC_PIN_48V GPIO_NUM_7
#define VP_ADC_SAMPLE_FREQ_HZ 4000
#define VP_ADC_APPROX_FULL_SCALE_MV 3300
#define VP_ADC_RATIO_24V_NUM 1
#define VP_ADC_RATIO_24V_DEN 1
#define VP_ADC_RATIO_5V_NUM 1
#define VP_ADC_RATIO_5V_DEN 1
#define VP_ADC_RATIO_36V_NUM 1
#define VP_ADC_RATIO_36V_DEN 1
#define VP_ADC_RATIO_48V_NUM 1
#define VP_ADC_RATIO_48V_DEN 1

/* 输出使能控制。EN 高有效，上电默认必须保持关闭。 */
#define VP_OUT_PIN_EN_48V GPIO_NUM_15
#define VP_OUT_PIN_EN_36V GPIO_NUM_16
#define VP_OUT_PIN_EN_24V GPIO_NUM_17
#define VP_OUTPUT_ENABLE_ACTIVE_LEVEL 1
#define VP_OUTPUT_ENABLE_INACTIVE_LEVEL 0
#define VP_OUTPUT_INTERLOCK_DELAY_MS 200

/* 预留 EEPROM/FRAM I2C 总线，用于后续 A/B 记录与 CRC 恢复。 */
#define VP_I2C_PORT 0
#define VP_I2C_PIN_SCL GPIO_NUM_35
#define VP_I2C_PIN_SDA GPIO_NUM_36
#define VP_I2C_CLOCK_HZ 400000
#define VP_STATE_SAVE_STABLE_MS 5000

/* 人机接口：按钮、蜂鸣器、系统灯。 */
#define VP_PIN_SCREEN_BUTTON GPIO_NUM_39
#define VP_PIN_BUZZER_PWM GPIO_NUM_40
#define VP_PIN_SYS_LED GPIO_NUM_41
#define VP_BUTTON_ACTIVE_LEVEL 0
#define VP_INPUT_DEBOUNCE_MS 50
#define VP_BUTTON_DOUBLE_CLICK_MS 350
#define VP_BUTTON_LONG_PRESS_MS 1500
#define VP_SYS_LED_ACTIVE_LEVEL 1
#define VP_BUZZER_LEDC_TIMER LEDC_TIMER_0
#define VP_BUZZER_LEDC_MODE LEDC_LOW_SPEED_MODE
#define VP_BUZZER_LEDC_CHANNEL LEDC_CHANNEL_0
#define VP_BUZZER_LEDC_DUTY_RES LEDC_TIMER_10_BIT
#define VP_BUZZER_LEDC_DUTY_ON 512

/* FreeRTOS 任务栈与优先级。 */
#define VP_TASK_STACK_SMALL 2048
#define VP_TASK_STACK_NORMAL 3072
#define VP_TASK_STACK_LARGE 4096
#define VP_TASK_PRIO_LOW 3
#define VP_TASK_PRIO_NORMAL 5
#define VP_TASK_PRIO_HIGH 7

#endif
