#ifndef VP_TYPES_H
#define VP_TYPES_H

#include <stdint.h>

#define VP_APP_TAG "VoltPilot"

/* ZJY122250-0213AJH-E5 panel: JD79661AA, 122(H) x 250(V), black/white/yellow/red. */
#define VP_EPD_DIAGONAL_INCH_X100 213
#define VP_EPD_CONTROLLER_NAME "JD79661AA"
#define VP_EPD_INTERFACE_NAME "4-wire SPI"
#define VP_EPD_MODULE_MODEL "ZJY122250-0213AJH-E5"
#define VP_EPD_PANEL_MODEL "ZJY122250-0213AJH-E5"
#define VP_EPD_WIDTH 122
#define VP_EPD_HEIGHT 250
#define VP_EPD_RAM_WIDTH 128
#define VP_EPD_DRIVER_GATE_COUNT 250
#define VP_EPD_PIXELS_PER_BYTE 4
#define VP_EPD_STRIDE_BYTES (VP_EPD_RAM_WIDTH / VP_EPD_PIXELS_PER_BYTE)
#define VP_EPD_PLANE_SIZE (VP_EPD_STRIDE_BYTES * VP_EPD_HEIGHT)
#define VP_EPD_COLOR_BLACK 0
#define VP_EPD_COLOR_WHITE 1
#define VP_EPD_COLOR_YELLOW 2
#define VP_EPD_COLOR_RED 3
#define VP_EPD_COLORS 4
#define VP_EPD_PARTIAL_REFRESH_SUPPORTED 0
#define VP_EPD_ACTIVE_WIDTH_UM 23705
#define VP_EPD_ACTIVE_HEIGHT_UM 48550
#define VP_EPD_MODULE_WIDTH_UM 30000
#define VP_EPD_MODULE_HEIGHT_UM 60200
#define VP_EPD_MODULE_THICKNESS_UM 2350
#define VP_EPD_PIXEL_PITCH_X_UM 194
#define VP_EPD_PIXEL_PITCH_Y_UM 194
#define VP_EPD_PANEL_VOLTAGE_MIN_MV 2200
#define VP_EPD_PANEL_VOLTAGE_MAX_MV 3700
#define VP_EPD_MODULE_SUPPLY_MV 3300
#define VP_EPD_GPIO_LEVEL_MAX_MV 3300
#define VP_EPD_MODULE_PIN_COUNT 8
#define VP_EPD_WEIGHT_MG 10000
#define VP_EPD_WEIGHT_TOLERANCE_MG 500

typedef enum {
    VP_OK = 0,
    VP_ERR = -1,
    VP_ERR_TIMEOUT = -2,
} vp_status_t;

#endif
