#ifndef VP_TYPES_H
#define VP_TYPES_H

#include <stdint.h>

#define VP_APP_TAG "VoltPilot"

/* 2.13 inch EPD panel, 122(H) x 250(V), black/white/yellow/red four-color flow. */
#define VP_EPD_DIAGONAL_INCH_X100 213
#define VP_EPD_CONTROLLER_NAME "JD79661AA"
#define VP_EPD_INTERFACE_NAME "4-wire SPI"
#define VP_EPD_MODULE_MODEL_BW "ZJYE213S08WOG01"
#define VP_EPD_MODULE_MODEL_BWR "ZJYE213S08ROG01"
#define VP_EPD_MODULE_MODEL_BWY "ZJYE213S08YOG01"
#define VP_EPD_PANEL_MODEL_BW "ZJY122250-0213BAAMFGN"
#define VP_EPD_PANEL_MODEL_BWR "ZJY122250-0213BBDMFGN-R"
#define VP_EPD_PANEL_MODEL_BWRY "ZJY122250-0213AJH-E5"
#define VP_EPD_WIDTH 122
#define VP_EPD_HEIGHT 250
#define VP_EPD_SOURCE_BITS 128
#define VP_EPD_GATE_BITS 250
#define VP_EPD_PIXELS_PER_BYTE 4
#define VP_EPD_WIDTH_BYTES (VP_EPD_SOURCE_BITS / VP_EPD_PIXELS_PER_BYTE)
#define VP_EPD_BUFFER_SIZE (VP_EPD_WIDTH_BYTES * VP_EPD_HEIGHT)
#define VP_EPD_COLOR_BLACK 0x00
#define VP_EPD_COLOR_WHITE 0x01
#define VP_EPD_COLOR_YELLOW 0x02
#define VP_EPD_COLOR_RED 0x03
#define VP_EPD_COLORS_BW 2
#define VP_EPD_COLORS_BWR 3
#define VP_EPD_COLORS_BWRY 4
#define VP_EPD_BW_PARTIAL_REFRESH_SUPPORTED 1
#define VP_EPD_COLOR_PARTIAL_REFRESH_SUPPORTED 0
#define VP_EPD_ACTIVE_WIDTH_UM 23705
#define VP_EPD_ACTIVE_HEIGHT_UM 48550
#define VP_EPD_PANEL_WIDTH_UM 29200
#define VP_EPD_PANEL_HEIGHT_UM 59200
#define VP_EPD_PANEL_THICKNESS_UM 1000
#define VP_EPD_PIXEL_PITCH_X_UM 194
#define VP_EPD_PIXEL_PITCH_Y_UM 194
#define VP_EPD_PANEL_VOLTAGE_MIN_MV 2200
#define VP_EPD_PANEL_VOLTAGE_MAX_MV 3700
#define VP_EPD_MODULE_SUPPLY_MV 3300
#define VP_EPD_GPIO_LEVEL_MAX_MV 3300
#define VP_EPD_FPC_PIN_COUNT 24
#define VP_EPD_FPC_PITCH_UM 500
#define VP_EPD_WEIGHT_MG 3200
#define VP_EPD_WEIGHT_TOLERANCE_MG 500

typedef enum {
    VP_OK = 0,
    VP_ERR = -1,
    VP_ERR_TIMEOUT = -2,
} vp_status_t;

#endif
